// Code generated by gengoos.go using 'go generate'. DO NOT EDIT.

//go:build ios
package sysvars

const GOOS = `ios`

const IsAix = false
const IsAndroid = false
const IsDarwin = false
const IsDragonfly = false
const IsFreebsd = false
const IsHurd = false
const IsIllumos = false
const IsIos = true
const IsJs = false
const IsLinux = false
const IsNetbsd = false
const IsOpenbsd = false
const IsPlan9 = false
const IsSolaris = false
const IsWindows = false
const IsZos = false
