// Code generated by gengoos.go using 'go generate'. DO NOT EDIT.

//go:build illumos
package sysvars

const GOOS = `illumos`

const IsAix = false
const IsAndroid = false
const IsDarwin = false
const IsDragonfly = false
const IsFreebsd = false
const IsHurd = false
const IsIllumos = true
const IsIos = false
const IsJs = false
const IsLinux = false
const IsNetbsd = false
const IsOpenbsd = false
const IsPlan9 = false
const IsSolaris = false
const IsWindows = false
const IsZos = false
